Updated core docs
intel/edge-hybrid-aisdk pull request #2
Opened 2024-04-01 15:34 UTC by srihari-humbarwadi-intel

2024-04-01 15:57 UTC, ck-intel requested changes

2024-04-01 15:57 UTC, ck-intel commented on docs/core/usage.md
> +### Loading the Desired Model
Loading the desired model and Specifying the inference backends can be merged as the underlying API is same, and in loading also a default backend is used.

2024-04-01 15:57 UTC, ck-intel commented on docs/core/usage.md
>  #### Loading Quantized Weights (INT8)
"Prepare" API description is missing, which can be used to compress OV model to int8.

2024-04-01 16:01 UTC, srihari-humbarwadi-intel commented on docs/core/usage.md
> +### Loading the Desired Model
its a subsection under `Loading the Desired Model`

2024-04-02 07:11 UTC, ck-intel approved these changes
LGTM

2024-04-02 07:15 UTC, merged